### ISSUE TITLE
error when installing on reddit: no image found with name "spritesheet" background-image: url(%%spritesheet%%);

### ISSUE THREAD

**Issue by bishopZ** [leb2/redmat#1]
[line 261] no image found with name "spritesheet"
       background-image: url(%%spritesheet%%);
[line 294] no image found with name "spritesheet"
           background-image: url(%%spritesheet%%);
[line 1108] no image found with name "spritesheet"
           background-image: url(%%spritesheet%%);
[line 1114] no image found with name "spritesheet"
             background-image: url(%%spritesheet%%);
[line 1119] no image found with name "spritesheet"
           background-image: url(%%spritesheet%%);

**Comment by joyhchen** [comment]
You need to upload the spritesheet that's located in images/spritesheet.png. Go to 'edit stylesheet' and find "images."  Upload your spritesheet there. 

Under each image you see something like "link:url(%%image-name%%)" Make sure you name your spritesheet 'spritesheet' when you upload it and it should work so that the text under it says 'link:url(%%spritesheet%%)'

**Comment by bishopZ** [comment]
yep, that worked! thanks.

Also, installing gulp globally with npm did not create it as a command-line utility (on mac).

I needed to add this to the package.json file

```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "gulp": "gulp"   
  },
```

once I had that I could run `npm run gulp` and things proceeded normally.

**Comment by bishopZ** [comment]
FYI, we got it up and running on /r/WebAnimation

**Comment by joyhchen** [comment]
Wow looks nice. I've actually never used this theme (chose to go with Naut and STCKY) but it looks great when applied. I think I might modify it a little and use it for my next subreddit style.
